language: python
python:
 - 2.6
 - 2.7

env:
 - DJANGO_VERSION="Django>=1.3.7,<1.4"
 - DJANGO_VERSION="Django==1.4.5"
 - DJANGO_VERSION="Django>=1.4.13,<1.5"
 - DJANGO_VERSION="Django>=1.5.8,<1.6"
 - DJANGO_VERSION="Django>=1.6.5,<1.7"
 - DJANGO_VERSION="Django>=1.7.8,<1.8"
 - DJANGO_VERSION="Django>=1.8,<1.9"

matrix:
    exclude:
        - python: 2.6
          env: DJANGO_VERSION="Django>=1.7.8,<1.8"
        - python: 2.6
          env: DJANGO_VERSION="Django>=1.8,<1.9"

install:
  - pip install -q $DJANGO_VERSION
  - pip install . pep8 pyflakes

script:
  - pep8 --max-line-length=140 django_zipkin/*.py
  - pyflakes django_zipkin/*.py
  - python setup.py test
